#! /usr/bin/ruby

unless Dir.exist?('test')
  puts contest = Dir.pwd[%r{(?<=contest/).*(?=/)}]
  puts number  = Dir.pwd[%r{(?<=/)\w$}]
  url = "https://atcoder.jp/contests/#{contest}/tasks/#{contest}_#{number}"
  `oj d #{url}`
  puts "-" * 20
end

`oj t -c "ruby main.rb"`

