#! /bin/bash

cd ~/Programming/contest
mkdir $1 || exit
cd $1

mkdir a
mkdir b
mkdir c
mkdir d
mkdir e

touch a/main.rb
touch b/main.rb
touch c/main.rb
touch d/main.rb
touch e/main.rb

echo "# $1 A" > a/main.rb
echo "# $1 B" > b/main.rb
echo "# $1 C" > c/main.rb
echo "# $1 D" > d/main.rb
echo "# $1 E" > e/main.rb

cat ~/Programming/contest/library/main.rb | tee -a a/main.rb | tee -a b/main.rb | tee -a c/main.rb | tee -a d/main.rb >> e/main.rb

echo "SET UP OK!!"
